### ISSUE TITLE
403 when installing the snap

### ISSUE THREAD

**Issue by imak** [Nightmayr-snaps/amazon-workspaces-snap#2]
On fedora 37, using latest snap, install fails with 403:

[imak@fedora ~]$ sudo snap install amz-workspaces
error: cannot perform the following tasks:
- Run configure hook of "amz-workspaces" snap if present (run hook "configure": 
-----
/usr/share/fonts: caching, new cache contents: 0 fonts, 37 dirs
/usr/share/fonts/aajohan-comfortaa-fonts: caching, new cache contents: 6 fonts, 0 dirs
...
/usr/share/fonts/urw-base35: skipping, looped directory detected
/usr/share/fonts/vazirmatn-vf-fonts: skipping, looped directory detected
/var/snap/amz-workspaces/common/fontconfig: cleaning cache directory
/usr/lib/fontconfig/cache: not cleaning non-existent cache directory
/snap/amz-workspaces/6/gnome-platform/usr/bin/fc-cache: succeeded
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/amz-workspaces/6/gnome-platform/usr/bin:/snap/amz-workspaces/6/bin:/snap/amz-workspaces/6/usr/bin:/var/snap/amz-workspaces/6/opt/workspacesclient
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/amz-workspaces/6/gnome-platform/usr/bin:/snap/amz-workspaces/6/bin:/snap/amz-workspaces/6/usr/bin:/var/snap/amz-workspaces/6/opt/workspacesclient
+ export LD_LIBRARY_PATH=/snap/amz-workspaces/6/gnome-platform/lib/x86_64-linux-gnu:/snap/amz-workspaces/6/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/amz-workspaces/6/gnome-platform/usr/lib:/snap/amz-workspaces/6/gnome-platform/lib:/snap/amz-workspaces/6/usr/lib:/snap/amz-workspaces/6/lib:/snap/amz-workspaces/6/usr/lib/x86_64-linux-gnu:/var/snap/amz-workspaces/6/opt/workspacesclient
+ LD_LIBRARY_PATH=/snap/amz-workspaces/6/gnome-platform/lib/x86_64-linux-gnu:/snap/amz-workspaces/6/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/amz-workspaces/6/gnome-platform/usr/lib:/snap/amz-workspaces/6/gnome-platform/lib:/snap/amz-workspaces/6/usr/lib:/snap/amz-workspaces/6/lib:/snap/amz-workspaces/6/usr/lib/x86_64-linux-gnu:/var/snap/amz-workspaces/6/opt/workspacesclient
+ '[' -f /var/snap/amz-workspaces/6/opt/workspacesclient/appsettings.json ']'
+ WORKSPACES_DEB=workspacesclient_4.3.0.1766_amd64.deb
+ wget https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu/dists/bionic/main/binary-amd64/workspacesclient_4.3.0.1766_amd64.deb -P /var/snap/amz-workspaces/6
--2023-01-23 20:31:40--  https://d3nt0h4h6pmmc4.cloudfront.net/ubuntu/dists/bionic/main/binary-amd64/workspacesclient_4.3.0.1766_amd64.deb
Resolving d3nt0h4h6pmmc4.cloudfront.net (d3nt0h4h6pmmc4.cloudfront.net)... 108.139.46.176, 108.139.46.202, 108.139.46.204, ...
Connecting to d3nt0h4h6pmmc4.cloudfront.net (d3nt0h4h6pmmc4.cloudfront.net)|108.139.46.176|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-01-23 20:31:40 ERROR 403: Forbidden.
-----)
[imak@fedora ~]$ cat /etc/fedora-release 
Fedora release 37 (Thirty Seven)
[imak@fedora ~]$ snap --version
snap    2.57.6-2.fc37
snapd   2.57.6-2.fc37
series  16
fedora  37
kernel  6.1.7-200.fc37.x86_64

**Comment by Nightmayr** [comment]
Looks like Amazon changed the URL for the deb again. I note you've made a fork of the repo with changes to the deb location. If those work do you want to create a PR against this repo? If not then no problem I can make the changes soon.

**Comment by dwivedi-ritik** [comment]
please do update it soon,  i am having the same issue

**Comment by Nightmayr** [comment]
I've pushed up a change that should get it working again. It'll be in the edge channel shortly

**Comment by Nightmayr** [comment]
Tested the edge channel and it worked for me. Promoted to stable
