### ISSUE TITLE
Snap will not connect on Fedora 36

### ISSUE THREAD

**Issue by Clifra-Jones** [Nightmayr-snaps/amazon-workspaces-snap#4]
Just upgraded to F-36, install this snap it fails to connect. 
"Unable to connect to your workspaces"
Workspace works in web client.

**Comment by Nightmayr** [comment]
I suspect it might be related to this issue https://github.com/Nightmayr-snaps/amazon-workspaces-snap/issues/3

I'll look to investigate over the next few days

**Comment by Nightmayr** [comment]
Pushed a change https://github.com/Nightmayr-snaps/amazon-workspaces-snap/commit/b2573a67f81aaeed4c1b113e5c07451b0855678a that got it to work for me. It will be in the edge channel and stable shortly
